### ISSUE TITLE
Require Descriptions for Pull Requests

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/api#151]
#### Description

To improve clarity and understanding of changes, all pull requests should include a brief description. 

### Actual Results example:

- Update index.php

### Expected example:

- Added a new feature to filter search results by date.
- Fixed a bug where search results were not displaying correctly when no filters were applied.

Purpose (optional):
- The new feature improves user experience by providing more relevant search results.
- The bug fix resolves issue #456 and enhances overall functionality.

**Comment by sebiboga** [comment]
you're right. will add more details about changes.
thank you @lalalaurentiu

**Comment by ale23yfm** [comment]
Now we write description about all changes
