### ISSUE TITLE
v1/background is loading forever

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/api#18]
**ENVIRONMENT**: TEST
      url: https://test.peviitor.ro
      browser: Chrome
      device: Laptop
      OS: Windows 

**STEPS TO REPRODUCE**:
   1) open url in browser
   2) click on v1/background
   3) click on Try it out
   4) click on Execute
   5) check results

**EXPECTED RESULTS**: 
  API is returning some results

**ACTUAL RESULTS**:
  API did not responded within  5 minutes, infinite loading icon is displayed

**Comment by ale23yfm** [comment]
v1/background does not exist anymore
