### ISSUE TITLE
Farmacia Tei - The number of jobs posted on Peviitor (1) and the one posted on the company website (22) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/api#22]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "FarmaciaTei" in the search bar.
3. Check the number of jobs available for FarmaciaTei.
4. Open "https://comenzi.farmaciatei.ro/cariere".
5. Scroll down and count the number of jobs displayed for each of the available locations.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 1 jobs posted on Peviitor website while on the company website there are posted 22 available jobs.

![farmaciatei peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/efccc5fe-97ea-4855-8504-e1bf293d1cd0)

![farmaciatei site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/4928086a-eebe-49e7-814c-1b373f9c6ec3)

**Comment by sebiboga** [comment]
@lalalaurentiu @andreireporter13 puteti verifica daca mai functioneaza acest scraper?

**Comment by lalalaurentiu** [comment]
@sebiboga you can close this issues because "Farmacia Tei" is not longer available.
