### ISSUE TITLE
api bug on swagger with the endpoint /random response

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#279]
ENVIROMENT: local swagger
URL: http://localhost:8080/swagger-ui/#/
Browser: Chrome
Device: PC
OS: Windows 10

**STEPS TO REPRODUCE:**

Open URL in browser
Open "/empty" endpoint.
Click on Try it out and Execute
Go on "/random" endpoint.
Click on "Try it out" and then on "Execute"
Verify the response body.

**Expected result:**
In the response body shouldn appear a message where it is announced the fact that all the jobs where deleted"
**Actual result:**
In the response body we have only a json code, with ""numFound": 0" without any message/announcement that all the jobs have been deleted..
<img width="1186" alt="swagger" src="https://github.com/user-attachments/assets/00bf1836-dde6-4971-8bd1-0a07882d0fb3">

**Comment by sebiboga** [comment]
APPROVED.
@ale23yfm we need to show a different message when the SOLR core is empty like : nu exista nici un loc de munca in baza de date
