### ISSUE TITLE
Wrong server response in the endpoint v0/jobs/ in swagger ui

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#285]
ENVIROMENT: local swagger
URL: http://localhost:8080/swagger-ui/#/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Open "/jobs" endpoint.
Click on Try it out .
Go on Parameters and type "a"
Click on  "Execute"
Verify the response body.

Expected results:
With "a" typing in the parameters text input the response should be 400

Actual results:
In the responses there is a 200 server response

**Comment by sebiboga** [comment]
please retest.
