### ISSUE TITLE
wrong response for v0/search endpoint on swagger ui

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#286]
ENVIROMENT: local swagger
URL: http://localhost:8080/swagger-ui/#/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Open "/search" endpoint.
Click on Try it out .
Go on q string on  Parameters and type any wrong text, as "abc233"
Click on  "Execute"
Verify the response body.

Expected results:
With a wrong text  typed in the "q strring"  parameters text input the response should be 400 or whatever error message which should said for example "not found"

Actual results:
In the responses there is a 200 server response and no error message.

**Comment by ale23yfm** [comment]
@DeedeeDL  can you review this please?

**Comment by DeedeeDL** [comment]
Retested. Pass
