### ISSUE TITLE
Different num found for endpoint /search/ for the same title of job with "" and without ""

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#298]
ENVIRONMENT:local
url: http://localhost:8080/swagger-ui/#/General/post_clean_
browser: Chrome
OS : Windows 10
STEPS TO REPRODUCE:
Open Docker
enter url in browser
Go to endpoint /search/
Type in the parameter q string "technical trainer"  and verify the num found, then type technical trainer without " " and verify the numfound

EXPECTED RESULTS:
The numfound should be the same

ACTUAL RESULTS:
There are different nums found .

**Comment by ale23yfm** [comment]
Aproved
