### ISSUE TITLE
Wrong response for v0/GET /search/ Search jobs for input with " at one side

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#325]
ENVIROMENT: local swagger
URL: http://localhost:8080/swagger-ui/#/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Open "/search" endpoint.
Click on Try it out .
Go on q string on Parameters and type a text with " at one side, example de"
Click on "Execute"
Verify the response body.

Expected results:
 the response should be 400 or whatever error message which should said for example "not found"

Actual results:
The response is failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

**Comment by ale23yfm** [comment]
I have 404 error code, please review this

![Image](https://github.com/user-attachments/assets/3234e852-f476-4789-81ce-ed561f653395)
