### ISSUE TITLE
Sandra Trading - The number of jobs from scrappers peviitor.ro is not the same as number of jobs peviitor.ro

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/api#34]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Sandra Trading" Company
3. Run scrapper for Company.
4. Check the number of the jobs.
5. Click on See jobs button.
6. Check the number of the jobs on peviitor.ro

EXPECTED RESULTS:
The number of jobs from scrappers peviitor.ro is the same as number of jobs peviitor.ro

ACTUAL RESULTS:
1. The number of jobs from scrappers peviitor.ro is not the same as number of jobs peviitor.ro
2. Two  of  the  5 jobs are taken from Linde company

![image](https://github.com/peviitor-ro/api/assets/71781611/9773f230-aaf8-4b35-b652-9b6297f28c1e)
![image](https://github.com/peviitor-ro/api/assets/71781611/cbcd1e7b-b13a-4ffa-8846-903f98518dfa)

![image](https://github.com/peviitor-ro/api/assets/71781611/cd6d1bfc-78f8-4fa5-9f48-92dfda79ae0f)

**Comment by sebiboga** [comment]
closing this issue
