### ISSUE TITLE
Response Header and Response from Vo/GET/search/search job are doubled

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#342]
ENVIROMENT: local
URL: http://localhost:8080/swagger-ui
OS: Windows 10
Browser:Chrome
Device : PC

STEPS TO REPRODUCE:
Open URL
Go on http://localhost:8080/swagger-ui/#
Go to GET/ search/ search job
Click on Try it out
Type inside Q string - Edutrust
Click on the button execute
Verify the response.
EXPECTED RESULTS:
In the response should be a "responseHeader" and a "response"

ACTUAL RESULTS:
The "responseHeader" and "response" appear twice.

**Comment by ale23yfm** [comment]
approved

**Comment by ale23yfm** [comment]
please review this

**Comment by DeedeeDL** [comment]
RETESTED.PASSED.
