### ISSUE TITLE
Wrong response in the endpoint V0 / Get/ get companies after deleting all the jobs from the core

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#344]
ENVIROMENT: local
URL:http://localhost:8080/swagger-ui/#/General/get_companies_
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Go to the endpoint GET/companies//get_companies
Click on try it out and Execute 
Verify the response 

Expected result:
There should be 0 companies or other message which says that all the jobs are deleted from the core.
Actual result:
In the response appears 1 company with the name string 

![Image](https://github.com/user-attachments/assets/a133c045-1b07-4788-8617-516d040f0b71)

**Comment by ale23yfm** [comment]
![Screenshot_20240730_152737](https://github.com/user-attachments/assets/830a6393-d34c-483b-b162-cd88a91ffb8e)
Please review this

**Comment by DeedeeDL** [comment]
Retested. PASS successfully. well done !
