### ISSUE TITLE
 Renault - The number of jobs on scrapers peviitor.ro is not the same as the number of jobs peviitor.ro

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/api#37]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for the " Renault" Company
3.Check the number of jobs
4.Open https://peviitor.ro/
5.Check the number of jobs

EXPECTED RESULTS:
The number of jobs posted on scrapers.peviitor.ro should match with the number of jobs posted on the peviitor.ro

ACTUAL RESULTS:
The number of jobs posted on scrapers.peviitor.ro is (108)
The number of jobs posted on the peviitor.ro is (110)
The number of jobs posted on website company is (108)

![image](https://github.com/peviitor-ro/api/assets/127322865/a422c296-2a7e-4eaa-8c7e-c02c35faf853)
![image](https://github.com/peviitor-ro/api/assets/127322865/0ebcf794-cc4b-42ec-a1d5-2c1f541b3176)
![image](https://github.com/peviitor-ro/api/assets/127322865/ceea5711-463e-4d83-8510-d59d88f885d1)

**Comment by sebiboga** [comment]
scrapers doesn't exist anymore
marked as obsolete
