### ISSUE TITLE
Hcltechnologies- The number of jobs posted on scrapers is different then the number of jobs posted on peviior and the one posted on company website

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/api#41]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/hcltechnologies/index.html
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in browser
2. Click on 'Run scraper' button
3. Check the number of jobs
4. Click on 'See jobs' button
5. Check the number of jobs
6.  Open https://www.hcltech.com/careers/romania
7. Count the jobs available

EXPECTED RESULTS:
The number of jobs posted on scrapers.peviitor.ro should match with the number of jobs posted on the peviitor.ro and with the number of jobs posted on company website

ACTUAL RESULTS:
The number of jobs posted on scrapers.peviitor.ro is (45)
The number of jobs posted on the peviitor.ro is (0)
The number of jobs posted on company website is (98)
![a39](https://github.com/peviitor-ro/api/assets/72222644/5e587abf-ee14-41ec-a4aa-ec4fd34ea92b)

**Comment by sebiboga** [comment]
scrapers doesn't exist anymore
marked as obsolete
