### ISSUE TITLE
Syncrosoft - The number of jobs posted on scrapers.peviitor.ro (1) is not the same as the number of jobs posted on the peviitor.ro(0)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/api#42]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Syncrosoft" Company
3. Check the number of jobs
4. Open https://peviitor.ro or click on "See Jobs" button
5. Check the number of jobs

EXPECTED RESULTS:
The number of jobs is the same on scrapers.peviitor.ro as on the peviitor.ro

ACTUAL RESULTS:
The number of jobs posted on scrapers.peviitor.ro (1) is not the same as the number of jobs posted on the peviitor.ro(0)

![image](https://github.com/peviitor-ro/api/assets/122023703/0540578a-309a-4854-a1dc-950f900c037a)
![image](https://github.com/peviitor-ro/api/assets/122023703/5157802b-9685-4ead-8fc7-00fa9cf02f96)

**Comment by sebiboga** [comment]
marking this as obsolete
