### ISSUE TITLE
v0/companies count query

### ISSUE THREAD

**Issue by ale23yfm** [peviitor-ro/api#437]
You have 3 choices "--", "true", "false".
If you select "--" it gives you 200 code, and does the same thing as "false". It must display 400 error Bad Request.

![image](https://github.com/user-attachments/assets/ebc7ecce-98f2-4cb9-b0c1-17769b207bc7)

**Comment by ale23yfm** [comment]
Daca selectezi "--" nu da eroare, iti apar numele companiilor, fara numarul de job-uri.

**Comment by sebiboga** [comment]
da, asa am scris codul... ca daca nu e TRUE atunci sa mearga pe ramura de FALSE din lipsa de timp....
daca vrei sa primesti 400 Bad Request fine by me, dar ce sa returneze in Body?
400 e Response Code
Bad Request e Response Message
ce returnam in Body?  {}

**Comment by sebiboga** [comment]
cu POSTMAN poti sa incerci mai multe test data. si daca scrii Bunica tot FALSE o sa il considere... deci ai multiple choices nu doar 3 choices
