### ISSUE TITLE
Plexus - The number of jobs posted on scrapers.peviitor.ro (83) is not the same as the number of jobs posted on the peviitor.ro(81), solr.peviitor.ro (81) and company website (82)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/api#44]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Plexus" Company
3. Check the number of jobs
4. Open https://peviitor.ro and check the number of the jobs
5. Open https://plexus.wd5.myworkdayjobs.com/Plexus_Careers?locationCountry=f2e609fe92974a55a05fc1cdc2852122 and check the number of the jobs
6. Open http://solr.peviitor.ro/
7. Execute Query for the "Plexus" Company and check the number of the jobs

EXPECTED RESULTS:
The number of jobs is the same on scrapers.peviitor.ro as on the peviitor.ro, solr.peviitor.ro and Company Website

ACTUAL RESULTS:
The number of jobs posted on scrapers.peviitor.ro (83) is not the same as the number of jobs posted on the peviitor.ro(81), solr.peviitor.ro (81) and company website (82)

![image](https://github.com/peviitor-ro/api/assets/122023703/98121582-f720-4f5c-9e33-942f458d04eb)

![image](https://github.com/peviitor-ro/api/assets/122023703/a316c870-9bb4-4bf1-84db-7f897f43976e)

![image](https://github.com/peviitor-ro/api/assets/122023703/0cc155f1-d85f-495b-95fc-088f85437c2d)

![image](https://github.com/peviitor-ro/api/assets/122023703/56bbb13d-82e2-40e8-ba03-fa7e9656784e)

**Comment by sebiboga** [comment]
marked as obsolete
