### ISSUE TITLE
Add logo not working

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/api#447]
https://github.com/user-attachments/assets/cf487335-4205-4136-b561-f31a46f12169

**Comment by AlexandruCoca99** [comment]
I tested the code on v0 which is the same as v1 and it works

**Comment by lalalaurentiu** [comment]
Is not working !!
![image](https://github.com/user-attachments/assets/6cc72754-be2e-4b10-b277-d40d7f8167e7)

**Comment by ale23yfm** [comment]
We do not have v1 swagger on http://api.peviitor.ro/
We moved it on http://peviitor.go.ro:8080/api/v1/swagger.json/

**Comment by lalalaurentiu** [comment]
@ale23yfm si nu mai e disponibile acest endpoint? "https://api.peviitor.ro/v1/logo/add/"

**Comment by lalalaurentiu** [comment]
Fixed #494
