### ISSUE TITLE
[QA] SOLR is not working 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#453]
URL:http://peviitor.go.ro/
Browser: Chrome
Device: PC
Operating system: windows 10

STEPS TO REPRODUCE:
Open http://peviitor.go.ro/

EXPECTED RESULTS:
SOLR si working 

ACTUAL RESULTS:.
SOLR is not working

**Comment by sebiboga** [comment]
this issue has been fixed by @AlexStefan17 
please retest

http://peviitor.go.ro/

**Comment by DeedeeDL** [comment]
Retested.Pass
