### ISSUE TITLE
[PERFORMANCE] Can we have monitoring tool for PROD?

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/api#454]
Hi @AlexStefan17 
 Can we have the monitoring tool for PROD environment? 
like we have it for QA:
![image](https://github.com/user-attachments/assets/90f0cf30-d768-4b4f-85d9-dfd758470dfd)

**Comment by AlexStefan17** [comment]
Installed Grafana + Prometheus on Prod server
