### ISSUE TITLE
API -The title must be "QA ENV" not "LOCAL ENV"

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/api#473]
URL:http://peviitor.go.ro:8080/swagger-ui/
Browser: Chrome
Device: PC
Operating system: windows 10

STEPS TO REPRODUCE:
Open http://peviitor.go.ro:8080/swagger-ui/
write in the search bar http://peviitor.go.ro:8080/api/v1/swagger.json

EXPECTED RESULTS:
The title for the swagger page is "API for QA Environment"

ACTUAL RESULTS:.
The title is "API for LOCAL ENV of peviitor.ro"

**Comment by AlexStefan17** [comment]
Hello @DeedeeDL,

Please retest

**Comment by DeedeeDL** [comment]
retested.passed. good job !
