### ISSUE TITLE
review all endpoints who use v0/server

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/api#71]
remove from every endpoint the usage of v0/server because this was already deleted and will no longer work

**Comment by ale23yfm** [comment]
@sebiboga should it be replaced or just removed? 
There is used v0/server, what should I do
https://github.com/peviitor-ro/api/blob/master/v0/search/test/index.php

**Comment by sebiboga** [comment]
@ale23yfm 
remove function get_master_server()
remove function get_server()
remove https://github.com/peviitor-ro/api/tree/master/v0/search/test endpoint
if you see get_master_server() function used, replace the server with the corresponding SOLR server URL:port we agreed

**Comment by ale23yfm** [comment]
We do not use it anymore
