### ISSUE TITLE
api.peviitor.ro SWAGGER UI should be able to test it locally

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/api#76]
@ale23yfm  we should be able to TEST locally swagger ui presented at https://api.peviitor.ro/
this task is about setup and configurations needed to be done to be able to verify swagger definitions for each endpoints BEFORE pushing them to PROD

this task includes:
* need to set COMPOSER locally
* adjust feed for swagger for localhost
* be sure we don't push code to PROD with localhost URL

**Comment by ale23yfm** [comment]
Now, we can test locally SqaggerUI
