### ISSUE TITLE
review v1/companies and push to v3/companies

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/api#83]
For now PROD is using v1/companies 
We need to keep v1 to push companies from QA and v3 from PROD

After that let's ask front-end team to use v3/companies instead of v1/companies

![image](https://github.com/peviitor-ro/api/assets/41440889/5c98efcc-a8d4-4a7a-b166-f1d245f67a8b)

**Comment by ale23yfm** [comment]
verified that v1/companies uses QA and v3/companies uses PROD and front-end team use v3/companies instead of v1/companies
